id: P2637A93C
initial_creation_type: ocr
source_metadata:
  volumes:
    caed63fe4e9e48b3973e84c9ed5fe139:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: རིགས་པ་དྲུག་ཅུ་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1605
      volume_number: 57
